// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KTe34okmj_rdyBIj9ja8kdR_yAPsy_Y',
    appId: '1:377509457953:web:c9ecdc54e6b1627d74f360',
    messagingSenderId: '377509457953',
    projectId: 'porkerapp-445c0',
    authDomain: 'porkerapp-445c0.firebaseapp.com',
    storageBucket: 'porkerapp-445c0.firebasestorage.app',
    measurementId: 'G-E3878R7BJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANyu5fEtXs4ak0hHvpvjQv64S0mquek9I',
    appId: '1:377509457953:android:00452745b7d8643674f360',
    messagingSenderId: '377509457953',
    projectId: 'porkerapp-445c0',
    storageBucket: 'porkerapp-445c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyF3_TuyJLyAau5Z7mXuNFn6HFhJpjJ8',
    appId: '1:377509457953:ios:0979e8a8f79bc5fa74f360',
    messagingSenderId: '377509457953',
    projectId: 'porkerapp-445c0',
    storageBucket: 'porkerapp-445c0.firebasestorage.app',
    iosBundleId: 'com.example.softbankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdyF3_TuyJLyAau5Z7mXuNFn6HFhJpjJ8',
    appId: '1:377509457953:ios:0979e8a8f79bc5fa74f360',
    messagingSenderId: '377509457953',
    projectId: 'porkerapp-445c0',
    storageBucket: 'porkerapp-445c0.firebasestorage.app',
    iosBundleId: 'com.example.softbankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KTe34okmj_rdyBIj9ja8kdR_yAPsy_Y',
    appId: '1:377509457953:web:28e5e408840fb7f374f360',
    messagingSenderId: '377509457953',
    projectId: 'porkerapp-445c0',
    authDomain: 'porkerapp-445c0.firebaseapp.com',
    storageBucket: 'porkerapp-445c0.firebasestorage.app',
    measurementId: 'G-69YQ2PF38T',
  );
}
